### ISSUE TITLE
Incluir testes adicionais para verificar chamada ao método match

### ISSUE THREAD

**Issue by fadc80** [thiagoarrais/como-testar#3]
Na implementação que usa [Spies](https://github.com/thiagoarrais/como-testar/tree/master/spies), o roteador sempre roteia a mensagem para o primeiro processador capaz de processá-la. Mesmo que existam outros processadores capazes de processar a mensagem, apenas o primeiro será acionado.

A capacidade de processamento é verificada através do método `match` do processador.

Seria interessante adicionar dois novos testes para verificar o acionamento desse método e documentar os seguintes comportamentos:

1. Quando a mensagem é impar, então o método match dos processadores par e impar são chamados.

2. Quando a mensagem é par, apenas o método match do processador impar é chamado.

A questão chave aqui é a ordem em que os processadores são adicionados no roteador. Os comportamentos citados seriam observados quando inserimos primeiro o processador de mensagens pares.

**Comment by fadc80** [comment]
Agora fiquei na dúvida se o ideal é criar novos testes ou incorporar isso nos testes existentes.

**Comment by fadc80** [comment]
Considerando a abordagem BDD do Jasmine estou pensando em reformular os testes que passariam a se autodescrever da seguinte maneira;

JSON Message Router Testing

1. When there is just a processor for each  message type, only the matching processor is called
1.1 Even messages are dispatched only to the EVEN processor.
1.2 Odd messages are dispatched only to the ODD processor.
2. When there are multiple matching processors for the same message type, only the first one is called
2.1 Two matching processors for EVEN messages, but just the first one is called.
2.2 Two matching processors for ODD messages, but just the first one is called.

**Comment by fadc80** [comment]
Certamente isso vai um pouco além do que propõe a descrição inicial desse issue.

**Comment by thiagoarrais** [comment]
O que seria mais idiomático em Jasmine?

Meu voto é fazer isso.

**Comment by thiagoarrais** [comment]
Merged #4
